name: Update TryHackMe Badge

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "skye.jen"
          user_public_id: "65e70a43bbad83d51ceb7c2a"
          use_static_image: false
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}